appName: user
replicaCount: 1
image:
  repository: 378784712135.dkr.ecr.us-east-1.amazonaws.com/user
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  name: dev

configmap:
  create: true
  content:
    MONGO_URL: "mongodb://mongo-mongodb:27017/users"
    REDIS_HOST: redis-master

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
